# Generated by Django 3.2 on 2022-10-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielist_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
